### ISSUE TITLE
How to use latest docker image?

### ISSUE THREAD

**Issue by alancwoo** [rclement/dokku-matomo#1]
Hello, thank you for this, I'm trying to update to use the latest image but get a 404 upon deploying. Do you have any idea how to go about this? It seems to be related to https://github.com/crazy-max/docker-matomo/issues/14 and needing to configure the `traefik.frontend.rule` in the `docker-compose.yml`

**Comment by rclement** [comment]
Hi @alancwoo,

First of all, I'm sorry but I haven't use the Dokku nor Matomo for a long time.

Concerning your issue, from what I can see, it is not related to Traefik: as explained in the mentioned related issue, this is only the case for the example with `docker-compose` the other developer is using. This is a completely different setup with Dokku as it does not use Traefik but NGinx if I remember correctly.

If not already done, please consult the Dokku documentation:

- [Dockerfile deployment](http://dokku.viewdocs.io/dokku~v0.20.3/deployment/methods/dockerfiles/)
- [Domain configuration](http://dokku.viewdocs.io/dokku~v0.20.3/configuration/domains/)
- [Nginx configuration](http://dokku.viewdocs.io/dokku~v0.20.3/configuration/nginx/)

I'm leaving this issue open until a solution can be found.

**Comment by mimischi** [comment]
@alancwoo See my pull request #2 that updates the `README.md` file. Deploying in this way has worked for me. ~I guess the update should also work.~ Updating from `3.12.0` to `3.13.5` was successful.

**Comment by alancwoo** [comment]
@mimischi sorry for the incredibly delayed reply and thank you so much for the help. I had to destroy the original app to get it working, but the initial install and also upgrading after the fact works properly via the updated instructions. Thank you :)

**Comment by mimischi** [comment]
Thanks for checking back in @alancwoo!
